### ISSUE TITLE
Async Task ne bi trebao biti napisan unutar activity-a

### ISSUE THREAD

**Issue by wideking** [gkovac42/factory-news-demo#1]
https://github.com/gkovac42/factory-news-demo/blob/434285554ca66e8564443f3d409f5a3790b5f2be/app/src/main/java/com/example/goran/factorynewsdemo/view/MainActivity.java#L62

Async task je dobro rješenje za dohvaćanje podataka,  super si napisao logiku za provjeru i dohvaćanje. Međutim postoji jedan mali problem, a a to je da je implementacija async task-a na ovaj način zapravo activity leak.  Jesi upoznat sa pojmom memory leak?

Vjerojatno si primjetio da je AsyncTask  objekt zapravo implementacija abstraktne klase.  Tvoja async task klasa se nalazi unutar druge klase koja se zove MainActivity, što znači da je async task inner klasa.  U javi, da bi se mogao napraviti objekt inner klase, on mora imati referencu na nadklasu, u ovom slučaju, MainActivity. Kao što znaš, Activity je Context componenta, vitalna za sustav. Kao takva, sustav ju može uništiti pa kada sustav to odluči ne bi nitko trebao imati referencu na nju kako bi se on mogao uništiti.

To ovdje nije slučaj, jer je Async task komponenta koja u pravilu može živiti duže od tvog Activity-a, ona nije vezana za život activity-a već za task koji mora izvršiti u pozadini, a normalno ponašanje je da neki task traje duže od activity-a.  

Nadam se da će ti ovo pomoći u shvaćanju problema. ako ne pitaj :)
 
Možeš li pretpostaviti kako bi trebalo riješiti ovaj problem?

**Comment by gkovac42** [comment]
Da ga izvučem u controller ili zasebnu klasu? Onda ga povežem sa viewom preko parametara ili interfejsa?

Uspio sam povući podatke preko Retrofita, pa sam mislio zamjeniti AsyncTask s njegovom onResponse metodom. To može ići u activity?

**Comment by wideking** [comment]
Mozes zamijeniti retrofitom ali je dobro da raspravimo o ovome jer je to
tradicionalni java problem.

Mozes li mi, iz perspektive programa, objasniti benefite izdvajenja u
zasebnu klasu i povezivanjem sa interdaceom?

**Comment by gkovac42** [comment]
Moram razmisliti o tome :)
Probat ću prvo u potpunosti preći na retrofit za dohvaćanje i cachiranje, pa ću vidjeti kako stoje stvari.

**Comment by gkovac42** [comment]
Prije nego push-am retrofit, je li ovakva implementacija AsyncTask-a bolja? Nije vise inner klasa, pa ne bi trrbalo biti leak-a...ili? Takodjer je cisci kod i blize single responsibility principu.

**Comment by gkovac42** [comment]
Implementirao sam AsyncTask kao zasebnu klasu. Je li ovako bolje?

**Comment by plavatvornica** [comment]
I prije je bio zasebna klasa, sada si samo popravio da komunicira sa activtijem preko listenera.  Imaš memory leak u async tasku i u onoj klasi što sam ti jučer rekao. Predlažem ti da prvo istražiš problem, da nađeš što bi moglo biti sumnjivo pa da onda analiziraš taj dio. U suprotnom ćeš se dovesti u situaciju gdje radiš posao više puta što najćešće rezultira i lošim kodom i nezadovljstvom svih koji su na projektu. 


Pogledaj te dvije klase, što one u sebi sadrže, kakav je njihov odnos sa android lifecycle komponentama?

**Comment by gkovac42** [comment]
Bi li možda trebao pozvati cancel() na AsyncTask iz Activity-a, u onStop ili onDestroy?

**Comment by wideking** [comment]
To bi ti bilo dobro da napraviš jer bi otpustio resurse koje ne koristiš -
dakle na on destroy jer ti prije toga može trebati. Za sada hladno. Obrati
pažnju ono što sam ti napisao u komentaru prije ovoga i izvornom komentaru.
u tim klasama držiš reference na android komponente. Ako te zbunjuje što bi
to moglo biti, kreni od početka - pronađi koje su to android komponente
koje govore sustavu tko je tvoja aplikacija, što radi screen, da li se
koristi itd...

**Comment by gkovac42** [comment]
Misliš na Context?

**Comment by wideking** [comment]
Da.

**Comment by wideking** [comment]
Možda ti ovaj video pomogne.
https://www.youtube.com/watch?v=BkbHeFHn8JY&index=33&list=PLWz5rJ2EKKc9CBxr3BVjPTPoDPLdPIFCE

**Comment by gkovac42** [comment]
Aha...evo čitam o tome, morat ću to malo dublje proučiti svakako. Za sada, da zamjenim context sa context.getApplicationContext?

**Comment by gkovac42** [comment]
Pisali smo u isto vrijeme :)... super, pogledat ću video, hvala.

I ne znam jesi vidio, imam mali problem sa retrofitom - novi issue.

**Comment by wideking** [comment]
Ovo sa contextom će riješiti jedan problem, u onoj data klasi, ostaje ti
problem u aync-u :)

**Comment by gkovac42** [comment]
Što je točno problem u async-u? Ne bih trebao u njemu raditi ništa što ima veze s view-om ili što? Lovim u mutnom sad već... :)

**Comment by wideking** [comment]
probam sa aysncom je listener koji mu postavljas da vratis podatke. taj
listener je zapravo tvoj activity, a taj listener ne mices nikada, sto
znaci da sve dok async task postaoji ce postojati i tvoja referenca na
activity.

**Comment by wideking** [comment]
Isti problem imas i sa inner klasama koje koristis kao listener-e :)

2017-11-15 21:28 GMT+01:00 Matija Solić <matija.solic@gmail.com>:

**Comment by gkovac42** [comment]
Koje bi onda bilo rješenje? Skoro svi primjeri koje sam našao koriste async kao inner klasu, a to smo u startu utvrdili da ne valja.

**Comment by gkovac42** [comment]
Je li WeakReference rješenje? (https://medium.com/@zhangqichuan/memory-leak-in-android-4a6a7e8d7780). Oprosti ako sam dosadan, ali baš me muči ovo sad :)

**Comment by plavatvornica** [comment]
Weak ref bi bilo jedno od riješenja :) drugo riješenje koje bi ti pomoglo da shvatiš ovaj problem je da makneš listenerer-e kada ti se aktivnost uništi, na taj način async task gubi poveznicu sa stvojim activity-em i on se može ponovo koristiti. Ovo riješenje će ti uvijek raditi dok weakRef neće jer netko drugi može imati strongRef na stvari iz weakRef-a pa ti se neće garbage collectati.

**Comment by gkovac42** [comment]
Nisam to znao, nemam bas puno iskustva sa interfejsima, ali sad shvacam. Hvala, zatvorit cu issue.
