### ISSUE TITLE
Implementirati image lib za manipulaciju slikama.

### ISSUE THREAD

**Issue by wideking** [gkovac42/factory-news-demo#2]
https://github.com/gkovac42/factory-news-demo/blob/434285554ca66e8564443f3d409f5a3790b5f2be/app/src/main/java/com/example/goran/factorynewsdemo/model/Article.java#L32

Vjerujem da si ovo dobro napravio, i da ovo funkcionira. Pretpostavljam da ti ovo nije bilo baš jednostanvo za napraviti te da si vjerojatno iskusio da app koristi puno memorije ili možda trza.  Razlog za ovo je praktički za svaki Article objekt držiš njegovu sliku u memoriji (byte array, odnosno kasnije bitmap). Slike su najteži podatak koji možeš imati jer sadrže puno informacija. Samim time zadaju i najviše muke :)  
Bolja ja praksa slike učitavati samo kada je potrebno, tj kada su spremne za prikaz. S time  da se učitavanje najčešće radi iz cache-a, kako bi bile što prije dostupne. Nema potrebe da ovo sam radiš, kao što sam rekao ovo je najtežža stvar za napraviti dobro i kvalitetno, bolje je tu jednostavno uzeti library-i. Naravno, puno ti pomaže to što znaš kako to radi u pozadini, pa će ti biti jednostavnije shvatiti zašto je neki library-i bolji ili lošiji za tvoje potrebe.

Preporučio bi ti fresco, to je fb-ov lib. Osim njega glide ti je dosta popularan. koji kod izabereš nećeš pogriješiti.

**Comment by gkovac42** [comment]
Implementirao sam Fresco. Vrlo jednostavno, a aplikacija se loada bar 5 puta brže! Super :)
Sad bi mi on trebao automatski spremati slike u cache? Ne moram pisati nikakv dodatni kod?

**Comment by wideking** [comment]
Fresco automatski ima postavljen cache koji mozes editirati, podesiti
velicinu i sl. Stvari.

Da li bi znao reći zašto se app loada puno brže?

**Comment by gkovac42** [comment]
Pretpostavljam da efikasnije koristi memoriju (pročitao sam da umjesto heap-a koristi ashmem). I nema suvišnih koraka kao kod moje metode - dekodiranje iz bitmapa u byte array, spremanje u bazu, ponovo dekodiranje u bitmap...

**Comment by wideking** [comment]
Sve je to tocno, ali nije to glavni razlog zasto je apo brzi. Obrati paznju
na to kada si prije ucitavao slike a kada ih sad ucitavas,  to ce ti
odgovoriti na pitanje :)

**Comment by gkovac42** [comment]
Učitava u zasebnom threadu?

**Comment by wideking** [comment]
Hladno, hladno. Pogledaj strukturu tvojih podataka prije i sada.

**Comment by gkovac42** [comment]
Bitmapi više nisu vezani za article objekte?

**Comment by wideking** [comment]
Jako toplo, sad to samo povezi s ovimr sto ti vec par puta govorim. Razlika
izmedu tog principa i ovog sto radi fresco. Kljucna stvar je kada ide poziv
za sliku i u koliko poziva..

**Comment by gkovac42** [comment]
Pa kada recycler pravi view, onoliko koliko mu treba u tom trenutku. Ne ide sve odjednom kao prije.

**Comment by wideking** [comment]
Uprvo to. Prije si za sve podatke u bazi koje si imao ucitavao i slike.
Poprilicna razlika od toga i ovog pristupa. To sam zelio da shvatis. Na
mobileu si poprilicno ogranicem resursima, sto memorijom, sto procesorom.
Uvijek je bolje promislititi cijeli sustav, analizitati ato to znaci za
mobitel, sto to znaci za korisnika i onda naci kompromise tako da oboje
budu sretni.

Nadam se da ti je uvid u ovakvo razmisljanje pomoglo i da ces nastaviti u
tom smjeru :)

**Comment by gkovac42** [comment]
Promljeno na znanje!  :)
