### ISSUE TITLE
Koristiti gotove implementacije PagerAdaptera 

### ISSUE THREAD

**Issue by wideking** [gkovac42/factory-news-demo#3]
https://github.com/gkovac42/factory-news-demo/blob/434285554ca66e8564443f3d409f5a3790b5f2be/app/src/main/java/com/example/goran/factorynewsdemo/view/adapters/NewsPagerAdapter.java#L22

Pokušaj koristiti gotove implementacije PagerAdaptera, vezane za fragmente. ( FragmentPager ili FragmentStatePagerAdapter)

U prvom paragrafu su ti navedeni linkovi. 
https://developer.android.com/reference/android/support/v4/view/PagerAdapter.html

Za sada je svejedno koji izabereš ali bilo bi dobro da proučiš i uočiš razliku između dva tipa :)

**Comment by gkovac42** [comment]
Implementirao sam FragmentPagerAdapter.

**Comment by wideking** [comment]
Super implementirano. 
Znaš razliku između ta dva tipa adaptera?

**Comment by gkovac42** [comment]
Oba koriste fragmente, očito. Koliko sam skužio iz u dokumentacije,  FragmentStatePagerAdapter je bolji za veće količine podataka/fragmenata jer uništava fragmente koji nisu prikazani, a pri tome čuva saved state. FragmentPagerAdapter ih čuva u memoriji.

**Comment by wideking** [comment]
Tako je, pager želiš koristiti sa jednostavnim viewovima, state pager sa
složenim viewovima kojih ima više. U složeni view spada sve što zauzima
dosta memorije.

Za početak ti je dovoljno da to znaš,možeš zatvoriti issue.
uto, 14. stu 2017. u 23:14 Goran Kovač <notifications@github.com> napisao
je:
