### ISSUE TITLE
Implementirati parcelable

### ISSUE THREAD

**Issue by wideking** [gkovac42/factory-news-demo#4]
https://github.com/gkovac42/factory-news-demo/blob/82ce6fc5190fd9f96d31fd3558557818d4bc6998/app/src/main/java/com/example/goran/factorynewsdemo/view/adapters/PagerFragment.java#L35

Android više voli Parcelable implementaciju iako neki smatraju da na novijim androidima nema neke razlike. Probja napraviti da article implementira parcelable pa to koristi, čisto da vidiš razliku

**Comment by gkovac42** [comment]
Jesam. Nisam primjetio neku razliku, ali količina podataka je ionako mala pa je teško za ocjeniti...

**Comment by wideking** [comment]
Teško je primjetiti razliku, eventualno da napraviš test pa mjeriš vrijeme.
Ovo više spada u neka dobra načela. Za očekivati je da ćeš jednog dana
rabiti library koji koristi parcelable ili češ sam željeti napraviti
library-i koji može slati podatke pa je zgodno koristiti stari koje većina
ljudi koristi :)
uto, 14. stu 2017. u 23:18 Goran Kovač <notifications@github.com> napisao
je:
