### ISSUE TITLE
Koristiti new instanceMetodologiju za instancijaranje fragmenata

### ISSUE THREAD

**Issue by wideking** [gkovac42/factory-news-demo#5]
https://github.com/gkovac42/factory-news-demo/blob/82ce6fc5190fd9f96d31fd3558557818d4bc6998/app/src/main/java/com/example/goran/factorynewsdemo/view/adapters/NewsPagerAdapter.java#L28

Na ovom linku ti je pojašnjenje.

http://www.androiddesignpatterns.com/2012/05/using-newinstance-to-instantiate.html

Kada implementiraš reci mi da li vidiš benefite ovog pristupa ili misliš da ti je jednako dobro kada bi koristio instancijranje preko konstruktora?

**Comment by gkovac42** [comment]
Jesam. Čišći je kod ovako - ako bi na više mjesta instancirao fragment mogu mu podatke samo prosljediti kroz parametar umjesto svaki puta pisati kod za Bundle.

**Comment by wideking** [comment]
Tako je, fleksibilniji si sa izmjenama. Sličan princip se može koristiti i
za activitye, samo moraš biti svjestan da se activity može pokrenuti i iz
sustava pa to premošćuje tvoju metodu. Mi recimo koristimo taj princip i za
activitye bas zato da možemo sa jednog mjesta izmjeniti parametre. Ako
nemaš pitanja u vezi ovog, zatvori issue.
uto, 14. stu 2017. u 23:27 Goran Kovač <notifications@github.com> napisao
je:
