### ISSUE TITLE
retrofit cache problem

### ISSUE THREAD

**Issue by gkovac42** [gkovac42/factory-news-demo#6]
https://github.com/gkovac42/factory-news-demo/blob/39f2dd6df620ee16276aa4d6d22415d8fbbc1ab4/app/src/main/java/com/example/goran/factorynewsdemo/controller/RequestController.java#L40-L55

Primjetio sam sad da imam problem s retrofitom.  Gore je interceptor, cache max-age podešen na 5 min.
No kada u MainActivity-u provjeravam:
https://github.com/gkovac42/factory-news-demo/blob/39f2dd6df620ee16276aa4d6d22415d8fbbc1ab4/app/src/main/java/com/example/goran/factorynewsdemo/view/MainActivity.java#L82-L89
if (response.raw().cacheResponse() != null) mi uvijek vraća true, i nakon pola sata. Povuče nove podatke ali zbog provjere uvijek učitava parsirani sadržaj iz prefsa, tako da nakon nekog vremena imam naslove koji ne odgovaraju sadržaju. Novi sam sa retrofitom pa ne kužim, je li problem u interceptoru , provjeri ili nečem trećem?

**Comment by wideking** [comment]
Morao sam i ja malo googlati :) 
Priča ti je slijedeća. HTTP header kaže koliko dugo je podatak valjan. Ti ga sam postaviš na 5 min, iako je to nešto obično server diktira. Nakon što istekne pet minuta i netko zatraži podatke, tvoj retrofit provjeri header i ode na server ali i serveru pošalje taj cache header. Server mu javi da se podaci nisu promijenili pa on vrati da je podatak došao iz cache-a ( cacheResponse != null).

Na linku je to bolje objašnjeno:
https://futurestud.io/tutorials/retrofit-2-check-response-origin-network-cache-or-both

**Comment by gkovac42** [comment]
Ok, pročitao sam.
